// demoData.ts — hardcoded static dataset (Hashem family + Islam family),
// used when src/lib/dataSource.ts DATA_SOURCE === 'static'.
//
// Generated by running the raw API-shaped fixtures in demoApiData.ts
// through the same convertApiMembers() (src/lib/convertApiData.ts) that
// src/app/api/ext-members/route.ts uses for the live 'api' data source —
// so 'static' mode exercises the exact same conversion path, and the demo
// dataset itself only needs maintaining in one place (demoApiData.ts).

import type { Member } from './types';
import { convertApiMembers } from './convertApiData';
import { demoCoreMembers, demoTreeData } from './demoApiData';

// `succession` (an A/C transferred from one member to another) isn't part
// of the raw coremember/mtreedata shape — see demoApiData.ts's header — so
// it's layered on by hand here, same as it would need to be for the live
// data source too.
const SUCCESSIONS: Record<string, string> = {
  'DM-8': 'DS-44',   // → Simran Rahman
  'PW-6': 'PK-49',   // → his own wife, Kaniz Fatema
  'LM-11': 'LS-35',  // → Syed Abubakar Siddique
};

export const familyMembers: Member[] = convertApiMembers(demoCoreMembers, demoTreeData).map(m =>
  SUCCESSIONS[m.id] ? { ...m, succession: SUCCESSIONS[m.id] } : m,
);




